# Stellar specific configs

article:
  type: tech

avatar: https://youke1.picui.cn/s1/2025/09/14/68c69594b0c21.png
# logo: https://youke1.picui.cn/s1/2025/09/14/68c69594b0c21.png
favicon: https://youke1.picui.cn/s1/2025/09/14/68c69594b0c21.png
# logo: TODO
