# Stellar specific configs

article:
  type: tech

inject:
  head:
    - <link href="https://fonts.font.im/css?family=Merriweather+Sans|Noto+Sans" rel="stylesheet">
  script:

style:
  font-family:
    body: '"Merriweather Sans", "Noto Sans"'

comments:
  service: beaudar
  beaudar:
    repo: Mooooonkrui/beaudar
